[project]
name = "ai-agent"
version = "0.1.0"
description = "AI Agent Project"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.13.2",
    "langchain==0.2.16",
    "langchain-community==0.2.16",
    "langchain-core==0.2.38",
    "langchain-groq>=0.1.9",
    "langchain-openai>=0.1.23",
    "langgraph>=0.2.19",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.4.1",
    "tavily-python>=0.7.24",
    "torch>=2.0.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true